version: '2'
services:
    tweeter-app:
        image: tweeter
        external_links:
            - tweeter-mysql:mysql
        environment:
            - SPRING_PROFILES_ACTIVE=prod
            - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/tweeter?useUnicode=true&characterEncoding=utf8&useSSL=false
        ports:
            - 8080:8080
    tweeter-mysql:
        extends:
            file: mysql.yml
            service: tweeter-mysql
